spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none